CREATE USER PARKSHARK IDENTIFIED BY PARKSHARK;
GRANT CREATE SESSION TO PARKSHARK;
GRANT CREATE TABLE TO PARKSHARK;
GRANT CREATE SEQUENCE TO PARKSHARK;
ALTER DATABASE DEFAULT TABLESPACE users;
GRANT UNLIMITED TABLESPACE TO PARKSHARK;